import json
import os
import torch
import logging
from transformers import AutoModelForCausalLM, AutoTokenizer

# ==========================================
# HARDCODED PATHS FOR TESTING
# ==========================================
OCR_JSON_INPUT_PATH = r"C:\Projects\text_extraction\output\X51005230616.json"  # <--- ENTER OCR JSON PATH HERE
FINAL_JSON_OUTPUT_PATH = r"C:\Projects\text_extraction\output\enhanced_output.json"   # <--- Output filename

def load_ocr_data(file_path):
    """Loads the OCR JSON output generated by the Spatial Layout Reconstructor."""
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"OCR JSON not found at {file_path}")
    with open(file_path, 'r', encoding='utf-8') as f:
        return json.load(f)

def format_prompt(ocr_data):
    """Formats the OCR data into a prompt for Qwen3 Thinking Mode."""
    # Consolidate all rows into a single text representation for the LLM
    full_text = ""
    for page in ocr_data.get("pages", []):
        full_text += f"\n--- Page {page.get('page')} ---\n"
        for row in page.get("rows", []):
            full_text += row.get("rendered_line", "") + "\n"

    system_instruction = (
        "You are an expert document analyzer. Your task is to extract all meaningful fields " 
        "from the provided OCR text and return them in a structured JSON format. " 
        "Look for headers, labels, and corresponding values (e.g., Invoice #, Date, Amounts, Line Items)."
    )

    user_prompt = ( 
        f"Analyze the following OCR text and extract all fields into a valid JSON object. " 
        f"OCR TEXT:\n{full_text}\n\n" 
        f"OUTPUT FORMAT:\n{{ 'extracted_fields': {{...}} }}"
     )

    return system_instruction, user_prompt

def run_inference(system_instruction, user_prompt):
    """Runs inference on Qwen3-1.7B optimized for CPU."""
    model_id = "Qwen/Qwen3-1.7B" # Note: Ensure this is the correct HF path for Qwen3
    
    print(f"Loading model: {model_id} (CPU Mode)...")
    
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    
    # CPU Optimization: Using bfloat16 if supported, else float32
    # We use device_map="cpu" to force CPU usage
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="cpu",
        dtype=torch.float32, # Safer for general CPU inference
        trust_remote_code=True
    )

    messages = [
        {"role": "system", "content": system_instruction},
        {"role": "user", "content": user_prompt}
    ]
    
    # Apply chat template
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    # print(text)
    model_inputs = tokenizer([text], return_tensors="pt").to("cpu")

    print("Generating response (this may take a minute on CPU)...")
    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=2048,
        do_sample=True,
        temperature=0.1,
        top_p=0.9
    )
    
    # Extract only the newly generated tokens
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return response

def main():
    try:
        # 1. Load OCR Data
        print(f"Reading OCR data from: {OCR_JSON_INPUT_PATH}")
        ocr_data = load_ocr_data(OCR_JSON_INPUT_PATH)

        # 2. Prepare Prompt
        system_instruction, user_prompt = format_prompt(ocr_data)

        # 3. Run LLM
        raw_response = run_inference(system_instruction, user_prompt)

        # 4. Parse and Save JSON
        print("\n--- LLM Response Received ---")
        
        # Attempt to find JSON block in case the LLM adds markdown or extra text
        try:
            json_start = raw_response.find('{')
            json_end = raw_response.rfind('}') + 1
            json_str = raw_response[json_start:json_end]
            final_data = json.loads(json_str)
        except Exception as e:
            print(f"Warning: Failed to parse JSON directly. Saving raw response. Error: {e}")
            final_data = {"raw_output": raw_response}

        with open(FINAL_JSON_OUTPUT_PATH, 'w', encoding='utf-8') as f:
            json.dump(final_data, f, indent=4)
        
        print(f"\n[SUCCESS] Final extracted data saved to: {os.path.abspath(FINAL_JSON_OUTPUT_PATH)}")

    except Exception as e:
        print(f"[ERROR] {str(e)}")

if __name__ == "__main__":
    main()
